### ISSUE TITLE
Flag in `make down` remove volumes on production

### ISSUE THREAD

**Issue by adzialocha** [lazaruslabs/culturestake-provisioning#15]
The `-v` flag leads to unexpected data-loss on production when running `make down`:
https://github.com/bitspossessed/culturestake-provisioning/blob/main/Makefile#L14

One could check if the development environment is active and set the flag where it is helpful, otherwise not.

**Comment by ana0** [comment]
Thanks - we decided to deliberately drop production data for this deploy, given that none of it was "real" anyway. So this should be safe to run until this deploy is finished at least

**Comment by adzialocha** [comment]
> Thanks - we decided to deliberately drop production data for this deploy, given that none of it was "real" anyway. So this should be safe to run until this deploy is finished at least

Phew ok, I already thought I'd destroyed something :sweat_smile:
