### ISSUE TITLE
Add note in readme about which make scripts to use/not use sudo with

### ISSUE THREAD

**Issue by ana0** [lazaruslabs/culturestake-provisioning#5]
`make up` and `make down` may require sudo, but `make contracts` and `make subgraph` should not

**Comment by adzialocha** [comment]
This depends on how you installed docker, some users don't need to sudo docker (like lluna) 🙂. I would recommend to not hard-code this!

**Comment by ana0** [comment]
I know! I wouldn't hardcode it either, but instead note which commands *might* need sudo, and which ones really shouldn't (contracts & subgraph). Otherwise someone can end up with a `.tmp` folder owned by root, and confused about why
